name: im-react-hw
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: gcp.edp-epam.com

database:
  required: false


ingress:
  required: false

image:
  name: im-react-hw
  version: latest